# Generated by Django 3.2 on 2021-04-24 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uptime', '0002_check_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='is_up',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
